# Generated by Django 3.1.1 on 2020-09-20 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200920_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_edit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 7, 23, 48, 321145, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
