# Generated by Django 3.1.1 on 2020-09-26 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200920_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_edit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 10, 43, 18, 186046, tzinfo=utc)),
        ),
    ]
