# Generated by Django 3.1.1 on 2020-09-27 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200927_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='in_post',
            new_name='in_announce',
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_edit',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 8, 59, 8, 168323, tzinfo=utc)),
        ),
    ]
